<?php

namespace ContainerWUxWxOf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckSkillsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Commands\CheckSkillsCommand' shared autowired service.
     *
     * @return \App\Commands\CheckSkillsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Commands/CheckSkillsCommand.php';

        return $container->services['console.command.public_alias.App\\Commands\\CheckSkillsCommand'] = new \App\Commands\CheckSkillsCommand();
    }
}
