<?php

namespace Container9iaoP81;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Commands\MyCommand' shared autowired service.
     *
     * @return \App\Commands\MyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Commands/MyCommand.php';

        return $container->services['console.command.public_alias.App\\Commands\\MyCommand'] = new \App\Commands\MyCommand();
    }
}
